# Generated by Django 3.0.7 on 2021-03-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('votes1', models.IntegerField(default=0)),
                ('votes2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profileImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VotesIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.BooleanField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.Polls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='polls',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.User'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('votes', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poll_app.Comments')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.Polls')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.User')),
            ],
        ),
    ]
