# Generated by Django 3.0.7 on 2021-03-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Polls',
            new_name='Poll',
        ),
    ]
