# Generated by Django 3.0.7 on 2021-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_auto_20210312_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.SlugField(default='', max_length=300),
        ),
    ]
