# Generated by Django 3.0.7 on 2021-03-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_auto_20210312_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='slug',
            new_name='poll_slug',
        ),
    ]
