# Generated by Django 3.0.7 on 2021-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0008_auto_20210313_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
