# Generated by Django 3.0.7 on 2021-03-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0009_auto_20210313_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profileImage',
            new_name='profile_image',
        ),
    ]
